[tool.poetry]
name = "kursovaya-3"
version = "0.1.0"
description = ""
authors = ["Michael < sorokajr678@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flake8 = "^7.2.0"
black = "^25.1.0"
isort = "^6.0.1"
requests = "^2.32.3"
psycopg2 = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
# Максимальная длина строки
line-length = 119
exclude = '''
(
  /(
    | \.git          # в корне проекта
    )
)
'''


[tool.isort]
# максимальная длина строки
line_length = 119